# Generated by Django 5.0.7 on 2024-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_datareceivermodel_id_alter_datasendermodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.TextField()),
                ('encrypted_keyword', models.CharField(max_length=255)),
                ('privatekey', models.TextField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'UploadFileModel',
            },
        ),
    ]
