# Generated by Django 5.0.7 on 2024-07-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(null=True, upload_to='static\\Files'),
        ),
    ]
