# Generated by Django 5.0.7 on 2024-07-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadfilemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='iv',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
