# Generated by Django 5.0.7 on 2024-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadfilemodel_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='cdk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
