# Generated by Django 5.0.7 on 2024-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadfilemodel_cdk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(null=True, upload_to='static\\ReqFiles')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.TextField()),
                ('encrypted_keyword', models.CharField(max_length=255)),
                ('privatekey', models.TextField(max_length=255, null=True)),
                ('iv', models.TextField(max_length=255, null=True)),
                ('cdk', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
    ]
